replicaCount: 2

image:
  repository: sowr94/spring-boot-application
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets:
  - name: crewmeister-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "crewmeister-service-account"  # Corrected name for service account

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080  # Ensure the port is set correctly here

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: crewmeister-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccountName: "crewmeister-service-account"  # This is for manually specifying a service account name

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
