replicaCount: 2
image:
  repository: sowr94/spring-boot-application
  pullPolicy: IfNotPresent
  tag: latest
imagePullSecrets:
  - name: crewmeister-secret
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "crewmeister-service-account"  
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  port: 8080  
  type: ClusterIP
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: crewmeister-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
serviceAccountName: "crewmeister-service-account"
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
