replicaCount: 1

image:
  repository: sugesh23/devops-coding-challenge
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

env:
  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_WRITER_URL: jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: dev

mysql:
  image: mysql:8.0
  rootPassword: dev
  database: challenge

serviceAccount:
  create: true
  name: crewmeister-challenge
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

fullnameOverride: ""

prometheus:
  namespaceOverride: prometheus
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    service:
      type: LoadBalancer

grafana:
  namespaceOverride: grafana
  adminPassword: admin
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: grafana.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

argocd:
  namespaceOverride: argocd
  global:
    image:
      repository: argoproj/argocd
      tag: v2.1.7
  server:
    service:
      type: LoadBalancer