prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    service:
      type: LoadBalancer

grafana:
  adminPassword: admin
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: grafana.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []