name: CI pipleine creation for Spring Boot application

# This workflow is triggered whenever a new PR is created on the mentioned branch
on:
  push:
    branches:
      - feature/assignment-a
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        name: Checkout repository          

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'
      - name: Build project with Maven
        run: ./mvnw clean package -DskipTests 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sowr94
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: sowr94/spring-boot-application:latest
      # Step 6: Set up kubectl
      - name: Set up Kubernetes
        uses: azure/k8s-actions@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}  # Store your kubeconfig in GitHub Secrets

      # Step 7: Install Helm
      - name: Install Helm
        run: |
         curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Step 8: Deploy the Helm chart
      - name: Deploy with Helm
        run: |
          helm upgrade --install my-app-release ./my-helm-chart \
          --set image.repository=sowr94/spring-boot-application
          --set image.tag=latest \
          --namespace app-springboot
        

            