name: CI pipleine creation for Spring Boot application

# This workflow is triggered whenever a new PR is created on the mentioned branch
on:
  push:
    branches:
      - feature/assignment-a
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        name: Checkout repository          

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'

            