name: crewmeister-ci

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Code Quality Checks
      run: mvn verify

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/devops-coding-challenge:latest --push .

  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CREWMEISTER_GITHUB_TOKEN }}

    - name: Update tag in Kubernetes deployment manifest
      run: | 
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/devops-coding-challenge:${{ github.run_id }}|" kubernetes/deploy.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git add helm-crewmeister/values.yaml
        git commit -m "[CI]: Update devops-coding-challenge image tag"
        git push origin HEAD:main -f

