name: crewmeister-ci

on:
  push:
    branches:
      - main
      - feature/*
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
        audience: sts.amazonaws.com

    - name: Verify AWS Identity
      run: aws sts get-caller-identity
    
    - name: Check IAM Role
      run: aws iam get-role --role-name GitHubActions-EKS-Deploy

    - name: Verify OIDC Providers
      run: aws iam list-open-id-connect-providers    

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --name ${{ secrets.EKS_CLUSTER_NAME }} \
          --region ${{ secrets.AWS_REGION }} \
          --role-arn ${{ secrets.AWS_ROLE_ARN }} \
          --alias github-actions

    - name: Verify kubectl Installation
      run: |
        which kubectl
        kubectl version --client

    - name: Debug Kubernetes Access
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --role-arn ${{ secrets.AWS_ROLE_ARN }} --alias github-actions
        kubectl cluster-info
        kubectl get nodes
        kubectl get pods -n default

    - name: Deploy Helm Chart (Debug)
      run: |
        helm upgrade --install crewmeister-app helm/crewmeister-app \
          --namespace default \
          --create-namespace \
          --values helm/crewmeister-app/values.yaml \
          --timeout 10m \
          --debug \
          --wait
    
    - name: Debug Kubernetes State
      run: |
        kubectl get pods -n default -o wide
        kubectl describe pods -n default
        kubectl get events -n default --sort-by=.metadata.creationTimestamp

    - name: Verify Helm Deployment
      run: |
        helm list -n default
        kubectl get pods -n default
