name: crewmeister-ci

on: 
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  updatek8s:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials (OIDC)
      id: aws-creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
        audience: sts.amazonaws.com

    - name: Debug AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ steps.aws-creds.outputs.aws-access-key-id }}"
        echo "AWS_SECRET_ACCESS_KEY=${{ steps.aws-creds.outputs.aws-secret-access-key }}"
        echo "AWS_SESSION_TOKEN=${{ steps.aws-creds.outputs.aws-session-token }}"

    - name: Verify AWS Identity
      run: aws sts get-caller-identity

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --role-arn ${{ secrets.AWS_ROLE_ARN }}

    - name: Debug AWS Credentials Before Helm
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ steps.aws-creds.outputs.aws-access-key-id }}"
        echo "AWS_SECRET_ACCESS_KEY=${{ steps.aws-creds.outputs.aws-secret-access-key }}"
        echo "AWS_SESSION_TOKEN=${{ steps.aws-creds.outputs.aws-session-token }}"
        aws sts get-caller-identity

    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        cluster-name: ${{ secrets.EKS_CLUSTER_NAME }}
        cluster-role-arn: ${{ secrets.AWS_ROLE_ARN }}
        config-files: helm/crewmeister-app/values.yaml
        chart-path: helm/crewmeister-app
        namespace: default
        create-namespace: true
        name: crewmeister-app
        action: install
        dry-run: false
        update-deps: true
        aws-access-key-id: ${{ steps.aws-creds.outputs.aws-access-key-id }}  
        aws-secret-access-key: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
        aws-session-token: ${{ steps.aws-creds.outputs.aws-session-token }}
