name: crewmeister-ci

on:
  push:
    branches:
      - main
      - feature/*
permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
        audience: sts.amazonaws.com

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --role-arn ${{ secrets.AWS_ROLE_ARN }}

    - name: Verify Kubernetes Access
      run: kubectl get nodes

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install crewmeister-app helm/crewmeister-app \
          --namespace default \
          --create-namespace \
          --values helm/crewmeister-app/values.yaml \
          --wait

    - name: Verify Helm Deployment
      run: |
        helm list -n default
        kubectl get pods -n default
