apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage-db-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard  